services:
  - type: web
    name: questionnaire-saas
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run db:init && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: questionnaire-saas
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: questionnaire-saas-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SEED_ADMIN_NAME
        value: Admin User
      - key: SEED_ADMIN_EMAIL
        sync: false
      - key: SEED_ADMIN_PASSWORD
        sync: false

databases:
  - name: questionnaire-saas-db
    plan: starter
    postgresMajorVersion: "18"
